### ISSUE TITLE
DIALux objects cannot deserialise correctly

### ISSUE THREAD

**Issue by adecler** [BHoM/DIALux_Toolkit#76]
#### Description:
I am actually struggling to understand what is going on here. Those BHoM objects have been moved from the `oM` to the `Adapter` namespace:

```
BH.oM.Adapters.DIALux.Furnishing
BH.oM.Adapters.DIALux.Luminaire
BH.oM.Adapters.DIALux.LuminaireType
BH.oM.Adapters.DIALux.Project
BH.oM.Adapters.DIALux.Room
BH.oM.Adapters.DIALux.StfFile
BH.oM.Adapters.DIALux.Structure
BH.oM.Adapters.DIALux.Version
```

Those were available in the UI menus before and are not anymore because of that change. They also cannot deserialise anymore for the same reason. 

From what I can see in the code, those seems to be created for internal usage. So here's the suggestion for restoring compliace:
- Add those to the list of objects that cannot be versioned because they have been deleted (at least from public eyes). I can take care of that although the message to the user will have to be written by someone that knows what is going on.
- Ask if they should really be BHoMObjects and fix it if the answer is `no`.

#### Steps to reproduce:
Test any of the objects above for versioning from the dataset of version 3.3 objects.

**Comment by FraserGreenroyd** [comment]
The change was made in [this PR](https://github.com/BHoM/DIALux_Toolkit/pull/66) and was done because when the toolkit was originally built, it was thought people might build up the objects within scripts. Workshops with users determined this to be not helpful and was providing more confusion as, by that point, we were pushing people to have a single model of Environment objects that the toolkit would handle conversions of, and building up very specific DIALux objects became non-sensical (similar to the gbXML objects within XML_Toolkit).

As such, the objects have been permanently moved from the oM and should be added to the list of objects that cannot be versioning. I am happy to draft up a message for that to be included in the `deleted.json` file or wherever such things are going in the versioning framework.

I would say the objects probably don't need to be BHoM objects anymore now they've moved from the oM though, so am happy to remove their inheritance. @JohannaOlin1 is that something you can pick up? :smile:

**Comment by adecler** [comment]
OK, I have added them to the list of deleted items. I'll ask everyone to add their message when I raise the PR

**Comment by FraserGreenroyd** [comment]
This is now being handled by [this PR](https://github.com/BHoM/Versioning_Toolkit/pull/134), specifically [this commit](https://github.com/BHoM/Versioning_Toolkit/pull/134/commits/9ce22fb954c9de1a0feb0f1cc17b9024c8e1d3fc) :smile:
